/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdmissionRecord = IDL.Record({
  'id' : IDL.Nat,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'course' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Nat,
  'username' : IDL.Text,
  'enrolledDate' : IDL.Int,
  'password' : IDL.Text,
  'role' : IDL.Text,
  'fullName' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'progress' : IDL.Nat,
  'phone' : IDL.Text,
  'course' : IDL.Text,
});
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'postedBy' : IDL.Text,
  'content' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ContactRecord = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const FranchiseRecord = IDL.Record({
  'id' : IDL.Nat,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'investment' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'ok' : IDL.Nat })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAdmissions' : IDL.Func(
      [],
      [IDL.Record({ 'ok' : IDL.Vec(AdmissionRecord) })],
      ['query'],
    ),
  'getAllStudents' : IDL.Func(
      [],
      [IDL.Record({ 'ok' : IDL.Vec(UserProfile) })],
      ['query'],
    ),
  'getAnnouncements' : IDL.Func(
      [],
      [IDL.Record({ 'ok' : IDL.Vec(Announcement) })],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactMessages' : IDL.Func(
      [],
      [IDL.Record({ 'ok' : IDL.Vec(ContactRecord) })],
      ['query'],
    ),
  'getFranchiseInquiries' : IDL.Func(
      [],
      [IDL.Record({ 'ok' : IDL.Vec(FranchiseRecord) })],
      ['query'],
    ),
  'getStudentProgress' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'ok' : UserProfile })],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginUser' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Record({ 'ok' : UserProfile })],
      ['query'],
    ),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'ok' : UserProfile })],
      [],
    ),
  'submitAdmission' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'ok' : IDL.Nat })],
      [],
    ),
  'submitContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'ok' : IDL.Nat })],
      [],
    ),
  'submitFranchiseInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'ok' : IDL.Nat })],
      [],
    ),
  'updateStudentProgress' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'updateUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'ok' : UserProfile })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdmissionRecord = IDL.Record({
    'id' : IDL.Nat,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'course' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Nat,
    'username' : IDL.Text,
    'enrolledDate' : IDL.Int,
    'password' : IDL.Text,
    'role' : IDL.Text,
    'fullName' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'progress' : IDL.Nat,
    'phone' : IDL.Text,
    'course' : IDL.Text,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'postedBy' : IDL.Text,
    'content' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ContactRecord = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const FranchiseRecord = IDL.Record({
    'id' : IDL.Nat,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'investment' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'ok' : IDL.Nat })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAdmissions' : IDL.Func(
        [],
        [IDL.Record({ 'ok' : IDL.Vec(AdmissionRecord) })],
        ['query'],
      ),
    'getAllStudents' : IDL.Func(
        [],
        [IDL.Record({ 'ok' : IDL.Vec(UserProfile) })],
        ['query'],
      ),
    'getAnnouncements' : IDL.Func(
        [],
        [IDL.Record({ 'ok' : IDL.Vec(Announcement) })],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactMessages' : IDL.Func(
        [],
        [IDL.Record({ 'ok' : IDL.Vec(ContactRecord) })],
        ['query'],
      ),
    'getFranchiseInquiries' : IDL.Func(
        [],
        [IDL.Record({ 'ok' : IDL.Vec(FranchiseRecord) })],
        ['query'],
      ),
    'getStudentProgress' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'ok' : UserProfile })],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginUser' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Record({ 'ok' : UserProfile })],
        ['query'],
      ),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'ok' : UserProfile })],
        [],
      ),
    'submitAdmission' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'ok' : IDL.Nat })],
        [],
      ),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'ok' : IDL.Nat })],
        [],
      ),
    'submitFranchiseInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'ok' : IDL.Nat })],
        [],
      ),
    'updateStudentProgress' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'updateUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'ok' : UserProfile })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };