/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdmissionRecord {
  'id' : bigint,
  'city' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
  'course' : string,
}
export interface Announcement {
  'id' : bigint,
  'title' : string,
  'postedBy' : string,
  'content' : string,
  'timestamp' : bigint,
}
export interface BrochureRequest {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'timestamp' : bigint,
  'phone' : string,
  'courseName' : string,
  'courseId' : bigint,
}
export interface ContactRecord {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface Course {
  'id' : bigint,
  'fee' : string,
  'title' : string,
  'duration' : string,
  'description' : string,
  'isActive' : boolean,
  'colorKey' : string,
  'topics' : Array<string>,
  'badge' : string,
  'subtitle' : string,
}
export interface FranchiseRecord {
  'id' : bigint,
  'city' : string,
  'name' : string,
  'investment' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface UserProfile {
  'id' : bigint,
  'username' : string,
  'enrolledDate' : bigint,
  'password' : string,
  'role' : string,
  'fullName' : string,
  'isActive' : boolean,
  'email' : string,
  'progress' : bigint,
  'phone' : string,
  'course' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAnnouncement' : ActorMethod<[string, string, string], { 'ok' : bigint }>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCourse' : ActorMethod<
    [string, string, string, string, string, string, Array<string>, string],
    bigint
  >,
  'deleteCourse' : ActorMethod<[bigint], boolean>,
  'getAdmissions' : ActorMethod<[], { 'ok' : Array<AdmissionRecord> }>,
  'getAllStudents' : ActorMethod<[], { 'ok' : Array<UserProfile> }>,
  'getAnnouncements' : ActorMethod<[], { 'ok' : Array<Announcement> }>,
  'getBrochureRequests' : ActorMethod<[], Array<BrochureRequest>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactMessages' : ActorMethod<[], { 'ok' : Array<ContactRecord> }>,
  'getCourses' : ActorMethod<[], { 'ok' : Array<Course> }>,
  'getFranchiseInquiries' : ActorMethod<[], { 'ok' : Array<FranchiseRecord> }>,
  'getStudentProgress' : ActorMethod<[string], bigint>,
  'getUserProfile' : ActorMethod<[string], { 'ok' : UserProfile }>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginUser' : ActorMethod<[string, string], { 'ok' : UserProfile }>,
  'registerUser' : ActorMethod<
    [string, string, string, string, string, string],
    { 'ok' : UserProfile }
  >,
  'submitAdmission' : ActorMethod<
    [string, string, string, string, string, string],
    { 'ok' : bigint }
  >,
  'submitBrochureRequest' : ActorMethod<
    [string, string, string, [] | [bigint], string],
    bigint
  >,
  'submitContact' : ActorMethod<
    [string, string, string, string],
    { 'ok' : bigint }
  >,
  'submitFranchiseInquiry' : ActorMethod<
    [string, string, string, string, string, string],
    { 'ok' : bigint }
  >,
  'updateCourse' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      Array<string>,
      string,
    ],
    boolean
  >,
  'updateStudentProgress' : ActorMethod<[string, bigint], boolean>,
  'updateUserProfile' : ActorMethod<
    [string, string, string, string],
    { 'ok' : UserProfile }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];